# Generated by gallery/generate.py; do not edit.
function chisel_gallery:clear
fill -80 99 -88 39 99 12 minecraft:stone
scoreboard players set #swatches chisel_gallery 0
scoreboard players set #structures chisel_gallery 0
scoreboard players set #controls chisel_gallery 0
setblock -72 100 -82 chisel:array/andesite
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -82 chisel:array/black_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -82 chisel:array/blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -82 chisel:array/bricks
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -82 chisel:array/brown_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -82 chisel:array/coal_block
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -82 chisel:array/cobblestone
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -82 chisel:array/cyan_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -82 chisel:array/deepslate
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -82 chisel:array/diorite
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -82 chisel:array/end_stone
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -82 chisel:array/glowstone
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -82 chisel:array/granite
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -82 chisel:array/gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -82 chisel:array/green_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -82 chisel:array/ice
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -82 chisel:array/light_blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -82 chisel:array/light_gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -82 chisel:array/lime_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -82 chisel:array/magenta_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -82 chisel:array/orange_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -82 chisel:array/pink_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -82 chisel:array/prismarine
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -80 chisel:array/purple_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -80 chisel:array/purpur
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -80 chisel:array/quartz
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -80 chisel:array/red_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -80 chisel:array/red_sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -80 chisel:array/redstone_block
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -80 chisel:array/sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -80 chisel:array/stone
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -80 chisel:array/white_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -80 chisel:array/yellow_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -80 chisel:braid/acacia_planks
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -80 chisel:braid/birch_planks
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -80 chisel:braid/crimson_planks
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -80 chisel:braid/dark_oak_planks
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -80 chisel:braid/jungle_planks
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -80 chisel:braid/oak_planks
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -80 chisel:braid/spruce_planks
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -80 chisel:bubble/glass
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -80 chisel:cells/diamond_block
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -80 chisel:chrono/glass
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -80 chisel:circular/andesite
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -80 chisel:circular/black_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -80 chisel:circular/blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -78 chisel:circular/bricks
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -78 chisel:circular/brown_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -78 chisel:circular/coal_block
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -78 chisel:circular/cobblestone
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -78 chisel:circular/cyan_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -78 chisel:circular/deepslate
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -78 chisel:circular/diorite
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -78 chisel:circular/end_stone
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -78 chisel:circular/granite
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -78 chisel:circular/gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -78 chisel:circular/green_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -78 chisel:circular/ice
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -78 chisel:circular/light_blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -78 chisel:circular/light_gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -78 chisel:circular/lime_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -78 chisel:circular/magenta_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -78 chisel:circular/orange_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -78 chisel:circular/pink_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -78 chisel:circular/prismarine
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -78 chisel:circular/purple_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -78 chisel:circular/purpur
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -78 chisel:circular/quartz
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -78 chisel:circular/red_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -76 chisel:circular/red_sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -76 chisel:circular/sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -76 chisel:circular/stone
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -76 chisel:circular/white_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -76 chisel:circular/yellow_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -76 chisel:cobble/dirt
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -76 chisel:crude_horizontal/acacia_planks
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -76 chisel:dent/andesite
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -76 chisel:dent/black_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -76 chisel:dent/blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -76 chisel:dent/bricks
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -76 chisel:dent/brown_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -76 chisel:dent/coal_block
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -76 chisel:dent/cobblestone
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -76 chisel:dent/cyan_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -76 chisel:dent/deepslate
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -76 chisel:dent/diorite
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -76 chisel:dent/end_stone
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -76 chisel:dent/glowstone
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -76 chisel:dent/granite
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -76 chisel:dent/gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -76 chisel:dent/green_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -76 chisel:dent/ice
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -74 chisel:dent/light_blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -74 chisel:dent/light_gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -74 chisel:dent/lime_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -74 chisel:dent/magenta_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -74 chisel:dent/orange_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -74 chisel:dent/pink_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -74 chisel:dent/prismarine
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -74 chisel:dent/purple_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -74 chisel:dent/purpur
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -74 chisel:dent/quartz
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -74 chisel:dent/red_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -74 chisel:dent/red_sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -74 chisel:dent/redstone_block
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -74 chisel:dent/sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -74 chisel:dent/stone
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -74 chisel:dent/white_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -74 chisel:dent/yellow_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -74 chisel:encased/acacia_planks
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -74 chisel:encased/birch_planks
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -74 chisel:encased/crimson_planks
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -74 chisel:encased/dark_oak_planks
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -74 chisel:encased/jungle_planks
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -74 chisel:encased/oak_planks
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -72 chisel:encased/spruce_planks
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -72 chisel:encased_bricks/andesite
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -72 chisel:encased_bricks/black_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -72 chisel:encased_bricks/blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -72 chisel:encased_bricks/bricks
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -72 chisel:encased_bricks/brown_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -72 chisel:encased_bricks/coal_block
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -72 chisel:encased_bricks/cobblestone
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -72 chisel:encased_bricks/cyan_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -72 chisel:encased_bricks/deepslate
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -72 chisel:encased_bricks/diorite
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -72 chisel:encased_bricks/end_stone
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -72 chisel:encased_bricks/glowstone
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -72 chisel:encased_bricks/granite
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -72 chisel:encased_bricks/gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -72 chisel:encased_bricks/green_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -72 chisel:encased_bricks/ice
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -72 chisel:encased_bricks/light_blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -72 chisel:encased_bricks/light_gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -72 chisel:encased_bricks/lime_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -72 chisel:encased_bricks/magenta_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -72 chisel:encased_bricks/orange_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -72 chisel:encased_bricks/pink_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -70 chisel:encased_bricks/prismarine
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -70 chisel:encased_bricks/purple_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -70 chisel:encased_bricks/purpur
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -70 chisel:encased_bricks/quartz
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -70 chisel:encased_bricks/red_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -70 chisel:encased_bricks/red_sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -70 chisel:encased_bricks/redstone_block
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -70 chisel:encased_bricks/sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -70 chisel:encased_bricks/stone
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -70 chisel:encased_bricks/white_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -70 chisel:encased_bricks/yellow_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -70 chisel:encased_large/acacia_planks
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -70 chisel:encased_large/birch_planks
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -70 chisel:encased_large/crimson_planks
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -70 chisel:encased_large/dark_oak_planks
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -70 chisel:encased_large/jungle_planks
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -70 chisel:encased_large/oak_planks
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -70 chisel:encased_large/spruce_planks
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -70 chisel:encased_smooth/acacia_planks
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -70 chisel:encased_smooth/birch_planks
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -70 chisel:encased_smooth/crimson_planks
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -70 chisel:encased_smooth/dark_oak_planks
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -70 chisel:encased_smooth/jungle_planks
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -68 chisel:encased_smooth/oak_planks
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -68 chisel:encased_smooth/spruce_planks
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -68 chisel:jellybean/andesite
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -68 chisel:jellybean/black_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -68 chisel:jellybean/blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -68 chisel:jellybean/bricks
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -68 chisel:jellybean/brown_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -68 chisel:jellybean/coal_block
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -68 chisel:jellybean/cobblestone
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -68 chisel:jellybean/cyan_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -68 chisel:jellybean/deepslate
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -68 chisel:jellybean/diorite
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -68 chisel:jellybean/end_stone
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -68 chisel:jellybean/glowstone
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -68 chisel:jellybean/granite
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -68 chisel:jellybean/gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -68 chisel:jellybean/green_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -68 chisel:jellybean/ice
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -68 chisel:jellybean/light_blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -68 chisel:jellybean/light_gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -68 chisel:jellybean/lime_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -68 chisel:jellybean/magenta_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -68 chisel:jellybean/orange_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -66 chisel:jellybean/pink_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -66 chisel:jellybean/prismarine
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -66 chisel:jellybean/purple_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -66 chisel:jellybean/purpur
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -66 chisel:jellybean/quartz
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -66 chisel:jellybean/red_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -66 chisel:jellybean/red_sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -66 chisel:jellybean/redstone_block
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -66 chisel:jellybean/sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -66 chisel:jellybean/stone
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -66 chisel:jellybean/white_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -66 chisel:jellybean/yellow_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -66 chisel:large/acacia_planks
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -66 chisel:large/birch_planks
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -66 chisel:large/crimson_planks
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -66 chisel:large/dark_oak_planks
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -66 chisel:large/jungle_planks
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -66 chisel:large/oak_planks
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -66 chisel:large/spruce_planks
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -66 chisel:large_tile/andesite
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -66 chisel:large_tile/black_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -66 chisel:large_tile/blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -66 chisel:large_tile/bricks
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -64 chisel:large_tile/brown_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -64 chisel:large_tile/coal_block
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -64 chisel:large_tile/cobblestone
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -64 chisel:large_tile/cyan_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -64 chisel:large_tile/deepslate
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -64 chisel:large_tile/diorite
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -64 chisel:large_tile/end_stone
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -64 chisel:large_tile/glowstone
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -64 chisel:large_tile/granite
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -64 chisel:large_tile/gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -64 chisel:large_tile/green_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -64 chisel:large_tile/ice
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -64 chisel:large_tile/light_blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -64 chisel:large_tile/light_gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -64 chisel:large_tile/lime_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -64 chisel:large_tile/magenta_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -64 chisel:large_tile/orange_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -64 chisel:large_tile/pink_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -64 chisel:large_tile/prismarine
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -64 chisel:large_tile/purple_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -64 chisel:large_tile/purpur
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -64 chisel:large_tile/quartz
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -64 chisel:large_tile/red_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -62 chisel:large_tile/red_sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -62 chisel:large_tile/redstone_block
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -62 chisel:large_tile/sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -62 chisel:large_tile/stone
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -62 chisel:large_tile/white_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -62 chisel:large_tile/yellow_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -62 chisel:legacy/black_wool
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -62 chisel:legacy/blue_wool
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -62 chisel:legacy/brown_wool
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -62 chisel:legacy/cyan_wool
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -62 chisel:legacy/gray_wool
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -62 chisel:legacy/green_wool
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -62 chisel:legacy/light_blue_wool
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -62 chisel:legacy/light_gray_wool
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -62 chisel:legacy/lime_wool
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -62 chisel:legacy/magenta_wool
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -62 chisel:legacy/orange_wool
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -62 chisel:legacy/pink_wool
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -62 chisel:legacy/purple_wool
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -62 chisel:legacy/red_wool
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -62 chisel:legacy/white_wool
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -62 chisel:legacy/yellow_wool
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -62 chisel:light/glass
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -60 chisel:llama/black_wool
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -60 chisel:llama/blue_wool
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -60 chisel:llama/brown_wool
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -60 chisel:llama/cyan_wool
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -60 chisel:llama/gray_wool
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -60 chisel:llama/green_wool
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -60 chisel:llama/light_blue_wool
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -60 chisel:llama/light_gray_wool
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -60 chisel:llama/lime_wool
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -60 chisel:llama/magenta_wool
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -60 chisel:llama/orange_wool
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -60 chisel:llama/pink_wool
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -60 chisel:llama/purple_wool
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -60 chisel:llama/red_wool
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -60 chisel:llama/white_wool
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -60 chisel:llama/yellow_wool
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -60 chisel:log_bordered/acacia_planks
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -60 chisel:log_bordered/birch_planks
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -60 chisel:log_bordered/crimson_planks
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -60 chisel:log_bordered/dark_oak_planks
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -60 chisel:log_bordered/jungle_planks
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -60 chisel:log_bordered/oak_planks
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -60 chisel:log_bordered/spruce_planks
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -58 chisel:masonry/coal_block
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -58 chisel:masonry/emerald_block
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -58 chisel:masonry/lapis_block
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -58 chisel:mosaic/andesite
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -58 chisel:mosaic/black_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -58 chisel:mosaic/blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -58 chisel:mosaic/bricks
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -58 chisel:mosaic/brown_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -58 chisel:mosaic/coal_block
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -58 chisel:mosaic/cobblestone
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -58 chisel:mosaic/cyan_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -58 chisel:mosaic/deepslate
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -58 chisel:mosaic/diorite
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -58 chisel:mosaic/end_stone
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -58 chisel:mosaic/glowstone
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -58 chisel:mosaic/granite
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -58 chisel:mosaic/gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -58 chisel:mosaic/green_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -58 chisel:mosaic/ice
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -58 chisel:mosaic/light_blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -58 chisel:mosaic/light_gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -58 chisel:mosaic/lime_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -58 chisel:mosaic/magenta_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -56 chisel:mosaic/nether_brick
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -56 chisel:mosaic/orange_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -56 chisel:mosaic/pink_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -56 chisel:mosaic/prismarine
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -56 chisel:mosaic/purple_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -56 chisel:mosaic/purpur
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -56 chisel:mosaic/quartz
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -56 chisel:mosaic/red_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -56 chisel:mosaic/red_sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -56 chisel:mosaic/redstone_block
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -56 chisel:mosaic/sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -56 chisel:mosaic/stone
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -56 chisel:mosaic/white_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -56 chisel:mosaic/yellow_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -56 chisel:noborder/glass
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -56 chisel:ornatesteel/glass
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -56 chisel:paneling/acacia_planks
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -56 chisel:paneling/birch_planks
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -56 chisel:paneling/crimson_planks
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -56 chisel:paneling/dark_oak_planks
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -56 chisel:paneling/jungle_planks
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -56 chisel:paneling/oak_planks
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -56 chisel:paneling/spruce_planks
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -54 chisel:reinforced/dirt
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -54 chisel:reinforcedcobble/dirt
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -54 chisel:shale/glass
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -54 chisel:shipping_crate/acacia_planks
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -54 chisel:shipping_crate/birch_planks
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -54 chisel:shipping_crate/crimson_planks
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -54 chisel:shipping_crate/dark_oak_planks
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -54 chisel:shipping_crate/jungle_planks
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -54 chisel:shipping_crate/oak_planks
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -54 chisel:shipping_crate/spruce_planks
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -54 chisel:slant/andesite
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -54 chisel:slant/black_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -54 chisel:slant/blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -54 chisel:slant/bricks
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -54 chisel:slant/brown_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -54 chisel:slant/coal_block
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -54 chisel:slant/cobblestone
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -54 chisel:slant/cyan_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -54 chisel:slant/deepslate
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -54 chisel:slant/diorite
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -54 chisel:slant/end_stone
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -54 chisel:slant/glowstone
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -54 chisel:slant/granite
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -52 chisel:slant/gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -52 chisel:slant/green_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -52 chisel:slant/ice
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -52 chisel:slant/light_blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -52 chisel:slant/light_gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -52 chisel:slant/lime_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -52 chisel:slant/magenta_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -52 chisel:slant/nether_brick
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -52 chisel:slant/orange_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -52 chisel:slant/pink_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -52 chisel:slant/prismarine
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -52 chisel:slant/purple_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -52 chisel:slant/purpur
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -52 chisel:slant/quartz
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -52 chisel:slant/red_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -52 chisel:slant/red_sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -52 chisel:slant/redstone_block
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -52 chisel:slant/sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -52 chisel:slant/stone
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -52 chisel:slant/white_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -52 chisel:slant/yellow_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -52 chisel:smooth/acacia_planks
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -52 chisel:smooth/birch_planks
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -50 chisel:smooth/crimson_planks
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -50 chisel:smooth/dark_oak_planks
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -50 chisel:smooth/jungle_planks
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -50 chisel:smooth/oak_planks
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -50 chisel:smooth/spruce_planks
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -50 chisel:steelframe/glass
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -50 chisel:stone/glass
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -50 chisel:sunken/deepslate
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -50 chisel:sunken/stone
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -50 chisel:weaver/andesite
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -50 chisel:weaver/black_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -50 chisel:weaver/blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -50 chisel:weaver/bricks
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -50 chisel:weaver/brown_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -50 chisel:weaver/coal_block
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -50 chisel:weaver/cobblestone
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -50 chisel:weaver/cyan_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -50 chisel:weaver/deepslate
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -50 chisel:weaver/diorite
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -50 chisel:weaver/end_stone
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -50 chisel:weaver/granite
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -50 chisel:weaver/gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -50 chisel:weaver/green_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -48 chisel:weaver/ice
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -48 chisel:weaver/light_blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -48 chisel:weaver/light_gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -48 chisel:weaver/lime_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -48 chisel:weaver/magenta_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -48 chisel:weaver/orange_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -48 chisel:weaver/pink_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -48 chisel:weaver/prismarine
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -48 chisel:weaver/purple_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -48 chisel:weaver/purpur
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -48 chisel:weaver/quartz
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -48 chisel:weaver/red_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -48 chisel:weaver/red_sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -48 chisel:weaver/sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -48 chisel:weaver/stone
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -48 chisel:weaver/white_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -48 chisel:weaver/yellow_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -48 chisel:zag/andesite
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -48 chisel:zag/black_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -48 chisel:zag/blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -48 chisel:zag/bricks
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -48 chisel:zag/brown_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -48 chisel:zag/coal_block
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -46 chisel:zag/cobblestone
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -46 chisel:zag/cyan_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -68 100 -46 chisel:zag/deepslate
scoreboard players add #swatches chisel_gallery 1
setblock -66 100 -46 chisel:zag/diorite
scoreboard players add #swatches chisel_gallery 1
setblock -64 100 -46 chisel:zag/end_stone
scoreboard players add #swatches chisel_gallery 1
setblock -62 100 -46 chisel:zag/granite
scoreboard players add #swatches chisel_gallery 1
setblock -60 100 -46 chisel:zag/gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -58 100 -46 chisel:zag/green_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -56 100 -46 chisel:zag/ice
scoreboard players add #swatches chisel_gallery 1
setblock -54 100 -46 chisel:zag/light_blue_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -52 100 -46 chisel:zag/light_gray_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -50 100 -46 chisel:zag/lime_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -48 100 -46 chisel:zag/magenta_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -46 100 -46 chisel:zag/orange_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -44 100 -46 chisel:zag/pink_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -42 100 -46 chisel:zag/prismarine
scoreboard players add #swatches chisel_gallery 1
setblock -40 100 -46 chisel:zag/purple_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -38 100 -46 chisel:zag/purpur
scoreboard players add #swatches chisel_gallery 1
setblock -36 100 -46 chisel:zag/quartz
scoreboard players add #swatches chisel_gallery 1
setblock -34 100 -46 chisel:zag/red_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -32 100 -46 chisel:zag/red_sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -30 100 -46 chisel:zag/sandstone
scoreboard players add #swatches chisel_gallery 1
setblock -28 100 -46 chisel:zag/stone
scoreboard players add #swatches chisel_gallery 1
setblock -72 100 -44 chisel:zag/white_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -70 100 -44 chisel:zag/yellow_concrete
scoreboard players add #swatches chisel_gallery 1
setblock -73 100 -35 chisel:bubble/glass
setblock -72 100 -35 chisel:bubble/glass
setblock -71 100 -35 chisel:bubble/glass
setblock -73 100 -34 chisel:bubble/glass
setblock -72 100 -34 chisel:bubble/glass
setblock -71 100 -34 chisel:bubble/glass
setblock -73 100 -33 chisel:bubble/glass
setblock -72 100 -33 chisel:bubble/glass
setblock -71 100 -33 chisel:bubble/glass
scoreboard players add #structures chisel_gallery 1
setblock -64 100 -35 chisel:chrono/glass
setblock -63 100 -35 chisel:chrono/glass
setblock -62 100 -35 chisel:chrono/glass
setblock -64 100 -34 chisel:chrono/glass
setblock -63 100 -34 chisel:chrono/glass
setblock -62 100 -34 chisel:chrono/glass
setblock -64 100 -33 chisel:chrono/glass
setblock -63 100 -33 chisel:chrono/glass
setblock -62 100 -33 chisel:chrono/glass
scoreboard players add #structures chisel_gallery 1
setblock -55 100 -35 chisel:light/glass
setblock -54 100 -35 chisel:light/glass
setblock -53 100 -35 chisel:light/glass
setblock -55 100 -34 chisel:light/glass
setblock -54 100 -34 chisel:light/glass
setblock -53 100 -34 chisel:light/glass
setblock -55 100 -33 chisel:light/glass
setblock -54 100 -33 chisel:light/glass
setblock -53 100 -33 chisel:light/glass
scoreboard players add #structures chisel_gallery 1
setblock -46 100 -35 chisel:noborder/glass
setblock -45 100 -35 chisel:noborder/glass
setblock -44 100 -35 chisel:noborder/glass
setblock -46 100 -34 chisel:noborder/glass
setblock -45 100 -34 chisel:noborder/glass
setblock -44 100 -34 chisel:noborder/glass
setblock -46 100 -33 chisel:noborder/glass
setblock -45 100 -33 chisel:noborder/glass
setblock -44 100 -33 chisel:noborder/glass
scoreboard players add #structures chisel_gallery 1
setblock -37 100 -35 chisel:ornatesteel/glass
setblock -36 100 -35 chisel:ornatesteel/glass
setblock -35 100 -35 chisel:ornatesteel/glass
setblock -37 100 -34 chisel:ornatesteel/glass
setblock -36 100 -34 chisel:ornatesteel/glass
setblock -35 100 -34 chisel:ornatesteel/glass
setblock -37 100 -33 chisel:ornatesteel/glass
setblock -36 100 -33 chisel:ornatesteel/glass
setblock -35 100 -33 chisel:ornatesteel/glass
scoreboard players add #structures chisel_gallery 1
setblock -28 100 -35 chisel:shale/glass
setblock -27 100 -35 chisel:shale/glass
setblock -26 100 -35 chisel:shale/glass
setblock -28 100 -34 chisel:shale/glass
setblock -27 100 -34 chisel:shale/glass
setblock -26 100 -34 chisel:shale/glass
setblock -28 100 -33 chisel:shale/glass
setblock -27 100 -33 chisel:shale/glass
setblock -26 100 -33 chisel:shale/glass
scoreboard players add #structures chisel_gallery 1
setblock -19 100 -35 chisel:steelframe/glass
setblock -18 100 -35 chisel:steelframe/glass
setblock -17 100 -35 chisel:steelframe/glass
setblock -19 100 -34 chisel:steelframe/glass
setblock -18 100 -34 chisel:steelframe/glass
setblock -17 100 -34 chisel:steelframe/glass
setblock -19 100 -33 chisel:steelframe/glass
setblock -18 100 -33 chisel:steelframe/glass
setblock -17 100 -33 chisel:steelframe/glass
scoreboard players add #structures chisel_gallery 1
setblock -10 100 -35 chisel:stone/glass
setblock -9 100 -35 chisel:stone/glass
setblock -8 100 -35 chisel:stone/glass
setblock -10 100 -34 chisel:stone/glass
setblock -9 100 -34 chisel:stone/glass
setblock -8 100 -34 chisel:stone/glass
setblock -10 100 -33 chisel:stone/glass
setblock -9 100 -33 chisel:stone/glass
setblock -8 100 -33 chisel:stone/glass
scoreboard players add #structures chisel_gallery 1
setblock -73 100 -26 chisel:circular/ice
setblock -72 100 -26 chisel:circular/ice
setblock -71 100 -26 chisel:circular/ice
setblock -73 100 -25 chisel:circular/ice
setblock -72 100 -25 chisel:circular/ice
setblock -71 100 -25 chisel:circular/ice
setblock -73 100 -24 chisel:circular/ice
setblock -72 100 -24 chisel:circular/ice
setblock -71 100 -24 chisel:circular/ice
scoreboard players add #structures chisel_gallery 1
setblock -64 100 -26 chisel:dent/ice
setblock -63 100 -26 chisel:dent/ice
setblock -62 100 -26 chisel:dent/ice
setblock -64 100 -25 chisel:dent/ice
setblock -63 100 -25 chisel:dent/ice
setblock -62 100 -25 chisel:dent/ice
setblock -64 100 -24 chisel:dent/ice
setblock -63 100 -24 chisel:dent/ice
setblock -62 100 -24 chisel:dent/ice
scoreboard players add #structures chisel_gallery 1
setblock -55 100 -26 chisel:encased_bricks/ice
setblock -54 100 -26 chisel:encased_bricks/ice
setblock -53 100 -26 chisel:encased_bricks/ice
setblock -55 100 -25 chisel:encased_bricks/ice
setblock -54 100 -25 chisel:encased_bricks/ice
setblock -53 100 -25 chisel:encased_bricks/ice
setblock -55 100 -24 chisel:encased_bricks/ice
setblock -54 100 -24 chisel:encased_bricks/ice
setblock -53 100 -24 chisel:encased_bricks/ice
scoreboard players add #structures chisel_gallery 1
setblock -46 100 -26 chisel:large_tile/ice
setblock -45 100 -26 chisel:large_tile/ice
setblock -44 100 -26 chisel:large_tile/ice
setblock -46 100 -25 chisel:large_tile/ice
setblock -45 100 -25 chisel:large_tile/ice
setblock -44 100 -25 chisel:large_tile/ice
setblock -46 100 -24 chisel:large_tile/ice
setblock -45 100 -24 chisel:large_tile/ice
setblock -44 100 -24 chisel:large_tile/ice
scoreboard players add #structures chisel_gallery 1
setblock -37 100 -26 chisel:mosaic/ice
setblock -36 100 -26 chisel:mosaic/ice
setblock -35 100 -26 chisel:mosaic/ice
setblock -37 100 -25 chisel:mosaic/ice
setblock -36 100 -25 chisel:mosaic/ice
setblock -35 100 -25 chisel:mosaic/ice
setblock -37 100 -24 chisel:mosaic/ice
setblock -36 100 -24 chisel:mosaic/ice
setblock -35 100 -24 chisel:mosaic/ice
scoreboard players add #structures chisel_gallery 1
setblock -28 100 -26 chisel:weaver/ice
setblock -27 100 -26 chisel:weaver/ice
setblock -26 100 -26 chisel:weaver/ice
setblock -28 100 -25 chisel:weaver/ice
setblock -27 100 -25 chisel:weaver/ice
setblock -26 100 -25 chisel:weaver/ice
setblock -28 100 -24 chisel:weaver/ice
setblock -27 100 -24 chisel:weaver/ice
setblock -26 100 -24 chisel:weaver/ice
scoreboard players add #structures chisel_gallery 1
setblock -19 100 -26 chisel:log_bordered/crimson_planks
setblock -18 100 -26 chisel:log_bordered/crimson_planks
setblock -17 100 -26 chisel:log_bordered/crimson_planks
setblock -19 100 -25 chisel:log_bordered/crimson_planks
setblock -18 100 -25 chisel:log_bordered/crimson_planks
setblock -17 100 -25 chisel:log_bordered/crimson_planks
setblock -19 100 -24 chisel:log_bordered/crimson_planks
setblock -18 100 -24 chisel:log_bordered/crimson_planks
setblock -17 100 -24 chisel:log_bordered/crimson_planks
scoreboard players add #structures chisel_gallery 1
setblock -10 100 -26 chisel:array/diorite
setblock -9 100 -26 chisel:array/diorite
setblock -8 100 -26 chisel:array/diorite
setblock -10 100 -25 chisel:array/diorite
setblock -9 100 -25 chisel:array/diorite
setblock -8 100 -25 chisel:array/diorite
setblock -10 100 -24 chisel:array/diorite
setblock -9 100 -24 chisel:array/diorite
setblock -8 100 -24 chisel:array/diorite
scoreboard players add #structures chisel_gallery 1
setblock -73 100 -17 chisel:array/granite
setblock -72 100 -17 chisel:array/granite
setblock -71 100 -17 chisel:array/granite
setblock -73 100 -16 chisel:array/granite
setblock -72 100 -16 chisel:array/granite
setblock -71 100 -16 chisel:array/granite
setblock -73 100 -15 chisel:array/granite
setblock -72 100 -15 chisel:array/granite
setblock -71 100 -15 chisel:array/granite
scoreboard players add #structures chisel_gallery 1
setblock -64 100 -17 chisel:braid/acacia_planks
setblock -63 100 -17 chisel:braid/acacia_planks
setblock -62 100 -17 chisel:braid/acacia_planks
setblock -64 100 -16 chisel:braid/acacia_planks
setblock -63 100 -16 chisel:braid/acacia_planks
setblock -62 100 -16 chisel:braid/acacia_planks
setblock -64 100 -15 chisel:braid/acacia_planks
setblock -63 100 -15 chisel:braid/acacia_planks
setblock -62 100 -15 chisel:braid/acacia_planks
scoreboard players add #structures chisel_gallery 1
setblock -55 100 -17 chisel:braid/birch_planks
setblock -54 100 -17 chisel:braid/birch_planks
setblock -53 100 -17 chisel:braid/birch_planks
setblock -55 100 -16 chisel:braid/birch_planks
setblock -54 100 -16 chisel:braid/birch_planks
setblock -53 100 -16 chisel:braid/birch_planks
setblock -55 100 -15 chisel:braid/birch_planks
setblock -54 100 -15 chisel:braid/birch_planks
setblock -53 100 -15 chisel:braid/birch_planks
scoreboard players add #structures chisel_gallery 1
setblock -46 100 -17 chisel:braid/crimson_planks
setblock -45 100 -17 chisel:braid/crimson_planks
setblock -44 100 -17 chisel:braid/crimson_planks
setblock -46 100 -16 chisel:braid/crimson_planks
setblock -45 100 -16 chisel:braid/crimson_planks
setblock -44 100 -16 chisel:braid/crimson_planks
setblock -46 100 -15 chisel:braid/crimson_planks
setblock -45 100 -15 chisel:braid/crimson_planks
setblock -44 100 -15 chisel:braid/crimson_planks
scoreboard players add #structures chisel_gallery 1
setblock -37 100 -17 chisel:braid/dark_oak_planks
setblock -36 100 -17 chisel:braid/dark_oak_planks
setblock -35 100 -17 chisel:braid/dark_oak_planks
setblock -37 100 -16 chisel:braid/dark_oak_planks
setblock -36 100 -16 chisel:braid/dark_oak_planks
setblock -35 100 -16 chisel:braid/dark_oak_planks
setblock -37 100 -15 chisel:braid/dark_oak_planks
setblock -36 100 -15 chisel:braid/dark_oak_planks
setblock -35 100 -15 chisel:braid/dark_oak_planks
scoreboard players add #structures chisel_gallery 1
setblock -28 100 -17 chisel:braid/jungle_planks
setblock -27 100 -17 chisel:braid/jungle_planks
setblock -26 100 -17 chisel:braid/jungle_planks
setblock -28 100 -16 chisel:braid/jungle_planks
setblock -27 100 -16 chisel:braid/jungle_planks
setblock -26 100 -16 chisel:braid/jungle_planks
setblock -28 100 -15 chisel:braid/jungle_planks
setblock -27 100 -15 chisel:braid/jungle_planks
setblock -26 100 -15 chisel:braid/jungle_planks
scoreboard players add #structures chisel_gallery 1
setblock -19 100 -17 chisel:braid/oak_planks
setblock -18 100 -17 chisel:braid/oak_planks
setblock -17 100 -17 chisel:braid/oak_planks
setblock -19 100 -16 chisel:braid/oak_planks
setblock -18 100 -16 chisel:braid/oak_planks
setblock -17 100 -16 chisel:braid/oak_planks
setblock -19 100 -15 chisel:braid/oak_planks
setblock -18 100 -15 chisel:braid/oak_planks
setblock -17 100 -15 chisel:braid/oak_planks
scoreboard players add #structures chisel_gallery 1
setblock -10 100 -17 chisel:braid/spruce_planks
setblock -9 100 -17 chisel:braid/spruce_planks
setblock -8 100 -17 chisel:braid/spruce_planks
setblock -10 100 -16 chisel:braid/spruce_planks
setblock -9 100 -16 chisel:braid/spruce_planks
setblock -8 100 -16 chisel:braid/spruce_planks
setblock -10 100 -15 chisel:braid/spruce_planks
setblock -9 100 -15 chisel:braid/spruce_planks
setblock -8 100 -15 chisel:braid/spruce_planks
scoreboard players add #structures chisel_gallery 1
setblock -73 100 -8 chisel:circular/andesite
setblock -72 100 -8 chisel:circular/andesite
setblock -71 100 -8 chisel:circular/andesite
setblock -73 100 -7 chisel:circular/andesite
setblock -72 100 -7 chisel:circular/andesite
setblock -71 100 -7 chisel:circular/andesite
setblock -73 100 -6 chisel:circular/andesite
setblock -72 100 -6 chisel:circular/andesite
setblock -71 100 -6 chisel:circular/andesite
scoreboard players add #structures chisel_gallery 1
setblock -64 100 -8 chisel:circular/black_concrete
setblock -63 100 -8 chisel:circular/black_concrete
setblock -62 100 -8 chisel:circular/black_concrete
setblock -64 100 -7 chisel:circular/black_concrete
setblock -63 100 -7 chisel:circular/black_concrete
setblock -62 100 -7 chisel:circular/black_concrete
setblock -64 100 -6 chisel:circular/black_concrete
setblock -63 100 -6 chisel:circular/black_concrete
setblock -62 100 -6 chisel:circular/black_concrete
scoreboard players add #structures chisel_gallery 1
setblock -55 100 -8 chisel:circular/blue_concrete
setblock -54 100 -8 chisel:circular/blue_concrete
setblock -53 100 -8 chisel:circular/blue_concrete
setblock -55 100 -7 chisel:circular/blue_concrete
setblock -54 100 -7 chisel:circular/blue_concrete
setblock -53 100 -7 chisel:circular/blue_concrete
setblock -55 100 -6 chisel:circular/blue_concrete
setblock -54 100 -6 chisel:circular/blue_concrete
setblock -53 100 -6 chisel:circular/blue_concrete
scoreboard players add #structures chisel_gallery 1
setblock -46 100 -8 chisel:circular/bricks
setblock -45 100 -8 chisel:circular/bricks
setblock -44 100 -8 chisel:circular/bricks
setblock -46 100 -7 chisel:circular/bricks
setblock -45 100 -7 chisel:circular/bricks
setblock -44 100 -7 chisel:circular/bricks
setblock -46 100 -6 chisel:circular/bricks
setblock -45 100 -6 chisel:circular/bricks
setblock -44 100 -6 chisel:circular/bricks
scoreboard players add #structures chisel_gallery 1
setblock -37 100 -8 chisel:circular/brown_concrete
setblock -36 100 -8 chisel:circular/brown_concrete
setblock -35 100 -8 chisel:circular/brown_concrete
setblock -37 100 -7 chisel:circular/brown_concrete
setblock -36 100 -7 chisel:circular/brown_concrete
setblock -35 100 -7 chisel:circular/brown_concrete
setblock -37 100 -6 chisel:circular/brown_concrete
setblock -36 100 -6 chisel:circular/brown_concrete
setblock -35 100 -6 chisel:circular/brown_concrete
scoreboard players add #structures chisel_gallery 1
setblock -28 100 -8 chisel:circular/coal_block
setblock -27 100 -8 chisel:circular/coal_block
setblock -26 100 -8 chisel:circular/coal_block
setblock -28 100 -7 chisel:circular/coal_block
setblock -27 100 -7 chisel:circular/coal_block
setblock -26 100 -7 chisel:circular/coal_block
setblock -28 100 -6 chisel:circular/coal_block
setblock -27 100 -6 chisel:circular/coal_block
setblock -26 100 -6 chisel:circular/coal_block
scoreboard players add #structures chisel_gallery 1
setblock -19 100 -8 chisel:circular/cobblestone
setblock -18 100 -8 chisel:circular/cobblestone
setblock -17 100 -8 chisel:circular/cobblestone
setblock -19 100 -7 chisel:circular/cobblestone
setblock -18 100 -7 chisel:circular/cobblestone
setblock -17 100 -7 chisel:circular/cobblestone
setblock -19 100 -6 chisel:circular/cobblestone
setblock -18 100 -6 chisel:circular/cobblestone
setblock -17 100 -6 chisel:circular/cobblestone
scoreboard players add #structures chisel_gallery 1
setblock -9 100 -7 chisel:array/andesite
setblock -8 100 -7 chisel:array/andesite
setblock -9 100 -6 chisel:array/andesite
setblock -8 100 -6 chisel:array/andesite
scoreboard players add #structures chisel_gallery 1
setblock -72 100 2 chisel:array/ice
setblock -71 100 2 chisel:array/ice
setblock -72 100 3 chisel:array/ice
setblock -71 100 3 chisel:array/ice
scoreboard players add #structures chisel_gallery 1
setblock -63 100 2 chisel:jellybean/cobblestone
setblock -62 100 2 chisel:jellybean/cobblestone
setblock -63 101 2 chisel:jellybean/cobblestone
setblock -62 101 2 chisel:jellybean/cobblestone
scoreboard players add #structures chisel_gallery 1
setblock -54 100 2 chisel:jellybean/ice
setblock -53 100 2 chisel:jellybean/ice
setblock -54 101 2 chisel:jellybean/ice
setblock -53 101 2 chisel:jellybean/ice
scoreboard players add #structures chisel_gallery 1
setblock -45 100 2 chisel:slant/quartz
setblock -45 101 2 chisel:slant/quartz
setblock -45 100 3 chisel:slant/quartz
setblock -45 101 3 chisel:slant/quartz
scoreboard players add #structures chisel_gallery 1
setblock -36 100 2 chisel:zag/ice
setblock -36 101 2 chisel:zag/ice
setblock -36 100 3 chisel:zag/ice
setblock -36 101 3 chisel:zag/ice
scoreboard players add #structures chisel_gallery 1
setblock 9 100 2 chisel:braid/coal_block
scoreboard players add #controls chisel_gallery 1
setblock 12 100 2 minecraft:stone
scoreboard players add #controls chisel_gallery 1
function chisel_gallery:verify
tellraw @a [{"text":"Chisel gallery: "},{"score":{"name":"#checked","objective":"chisel_gallery"}},{"text":" checked placements, "},{"score":{"name":"#failures","objective":"chisel_gallery"}},{"text":" failures"}]
