# Generated by gallery/generate.py; do not edit.
fill -80 99 -88 -61 104 12 minecraft:air
fill -60 99 -88 -41 104 12 minecraft:air
fill -40 99 -88 -21 104 12 minecraft:air
fill -20 99 -88 -1 104 12 minecraft:air
fill 0 99 -88 19 104 12 minecraft:air
fill 20 99 -88 39 104 12 minecraft:air
